### ISSUE TITLE
The property has data, even if nothing has been entered

### ISSUE THREAD

**Issue by sebastiandammark** [limbo-works/Limbo.Umbraco.StructuredData#1]
When no cells have been created you still get this output
![image](https://user-images.githubusercontent.com/1575483/189322711-f646bed2-3928-4ddd-a504-7f5a7df24015.png)

It would be better if it was just `null`

**Comment by abjerner** [comment]
Hi @sebastiandammark 

It probably doesn't make sense to add this now. If this does, feel free to open the issue again 😉 

I did however remember this when building the [**LImbo Tables**](https://github.com/limbo-works/Limbo.Umbraco.Tables) package, so at least it works there 😄
